run:
  deadline: 5m
  modules-download-mode: readonly
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.pb\\.micro\\.go$"
linters:
  disable-all: false
  enable-all: false
  enable:
    - megacheck
    - staticcheck
    - deadcode
    - varcheck
    - gosimple
    - unused
    - prealloc
    - scopelint
    - gocritic
    - goimports
    - unconvert
    - govet
    - nakedret
    - structcheck
    - gosec
  disable:
    - maligned
    - interfacer
    - typecheck
    - dupl
